//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongVanManager.View
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongVan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CongVan()
        {
            this.PhanHois = new HashSet<PhanHoi>();
            this.LienHes = new HashSet<LienHe>();
        }
    
        public long MaCongVan { get; set; }
        public string MaLoaiCongVan { get; set; }
        public string NoiGui { get; set; }
        public string SoKyHieu { get; set; }
        public Nullable<int> SoCongVan { get; set; }
        public Nullable<System.DateTime> NgayCongVan { get; set; }
        public string TrichYeu { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public string GhiChu { get; set; }
        public string PDFScan { get; set; }
        public System.DateTime NgayXuLi { get; set; }
    
        public virtual LoaiCongVan LoaiCongVan { get; set; }
        public virtual LienHe LienHe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanHoi> PhanHois { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LienHe> LienHes { get; set; }
    }
}
