//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongVanManager.View
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDFScan1
    {
        public string PDFName { get; set; }
        public byte[] Content { get; set; }
    }
}
