//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongVanManager.View
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanHoi
    {
        public string MaPhanHoi { get; set; }
        public long MaCongVan { get; set; }
        public string TenTaiKhoan { get; set; }
        public string BinhLuan { get; set; }
    
        public virtual CongVan CongVan { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
