//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongVanManager
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using CongVanManager.View;

    public partial class LienHe
    {
        public LienHe()
        {
            this.CongVans = new HashSet<CongVan>();
            this.DanhSachNoiNhan = new HashSet<NoiNhan>();
        }

        public LienHe(View.LienHe lh)
        {
            Email = lh.Email;
            Name = lh.TenLienHe;
            this.CongVans = new HashSet<CongVan>();
            this.DanhSachNoiNhan = new HashSet<NoiNhan>();
        }
    
        public string Email { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CongVan> CongVans { get; set; }
        public virtual ICollection<NoiNhan> DanhSachNoiNhan { get; set; }

        private static ObservableCollection<LienHe> _db;
        public static ObservableCollection<LienHe> DB
        {
            get
            {
                if (_db == null)
                {
                    _db = new ObservableCollection<LienHe>();

                    foreach (View.LienHe cv in DataProvider.Ins.DB.LienHe)
                        _db.Add(new LienHe(cv));

                    _db.CollectionChanged += (obj, arg) =>
                    {
                        if (arg.Action == NotifyCollectionChangedAction.Move)
                            return;
                        if (arg.OldItems != null)
                            foreach (LienHe item in arg.OldItems)
                            {
                                var cvs = DataProvider.Ins.DB.LienHe;
                                cvs.Remove(cvs.Find(item.Email));
                            }
                        if (arg.NewItems != null)
                            foreach (LienHe item in arg.NewItems)
                                DataProvider.Ins.DB.LienHe.Add(item.ToLienHe());
                    };
                }
                return _db;
            }
            private set { }
        }

        private View.LienHe ToLienHe()
        {
            return new View.LienHe { Email = Email, TenLienHe = Name};
        }

        public static LienHe Get(View.LienHe lcv)
        {
            foreach (LienHe item in DB)
            {
                if (item.Email == lcv.Email)
                    return item;
            }
            return null;
        }
    }
}
