//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongVanManager
{
    using CongVanManager.ViewModel;
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    public partial class NoiNhan : ObservableObject
    {
        public virtual CongVan CongVan { get; set; }
        public virtual LienHe LienHe { get; set; }

        private static DelayedObservableCollection<NoiNhan> _db;
        public static DelayedObservableCollection<NoiNhan> DB
        {
            get
            {
                if (_db == null)
                    _db = new DelayedObservableCollection<NoiNhan>();
                return _db;
            }
            private set { }
        }
    }
}
