//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongVanManager
{
    using CongVanManager.ViewModel;
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    public partial class PhanHoi : ObservableObject
    {
        public int Id { get; set; }
        public string Comment { get; set; }
    
        public virtual CongVan CongVan { get; set; }
        public virtual User User { get; set; }

        private static DelayedObservableCollection<PhanHoi> _db;
        public static DelayedObservableCollection<PhanHoi> DB
        {
            get
            {
                if (_db == null)
                    _db = new DelayedObservableCollection<PhanHoi>();

                throw new NotImplementedException();

                return _db;
            }
            private set { }
        }
    }
}
