//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongVanManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public string SubscribedWatchlist { get; set; }
    
        public User TruongPhong { get; set; }
        public DateTime lastUpdated { get; set; }

        private static Setting _instance;
        public static Setting instance {
            get {
                if (_instance == null)
                    _instance = new Setting();
                return _instance;
            }
            private set { }
        }
    }
}
