//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongVanManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongVan
    {
        public CongVan()
        {
            this.DanhSachNoiNhan = new HashSet<NoiNhan>();
            this.PhanHois = new HashSet<PhanHoi>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SoKyHieu { get; set; }
        public Nullable<System.DateTime> NgayCongVan { get; set; }
        public string TrichYeu { get; set; }
        public string GhiChu { get; set; }
        public string PDFScanLocation { get; set; }
        public System.DateTime NgayXuLi { get; set; }
        public bool XacNhan { get; set; }
    
        public virtual LoaiCongVan LoaiCongVan { get; set; }
        public virtual LienHe LienHe { get; set; }
        public virtual ICollection<NoiNhan> DanhSachNoiNhan { get; set; }
        public virtual HopCongVan HopCongVan { get; set; }
        public virtual ICollection<PhanHoi> PhanHois { get; set; }
    }
}
