//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongVanManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public LienHe()
        {
            this.CongVans = new HashSet<CongVan>();
            this.DanhSachNoiNhan = new HashSet<NoiNhan>();
        }
    
        public string Email { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CongVan> CongVans { get; set; }
        public virtual ICollection<NoiNhan> DanhSachNoiNhan { get; set; }
    }
}
