//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongVanManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoiNhan
    {
        public int Id { get; set; }
    
        public virtual CongVan CongVan { get; set; }
        public virtual LienHe LienHe { get; set; }
    }
}
